# Generated by Django 4.2.6 on 2024-01-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
        ),
        migrations.AlterField(
            model_name='compra',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.21, max_digits=3),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
        ),
    ]
