# Generated by Django 4.2.6 on 2024-01-11 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAplicacion', '0002_alter_compra_importe_alter_compra_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='nombre',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='TiendaAplicacion.producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
