# Generated by Django 4.2.6 on 2024-01-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAplicacion', '0004_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='vip',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
